AJD-Archive/Kkeujeok_Backend

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/template/RspTemplate.java
> Feat(#1): 응답 템플릿 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/ControllerAdvice.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/dto/ErrorResponse.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/AccessDeniedGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/AuthGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/InvalidGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/NotFoundGroupException.java
> Feat(#1): 전역 예외처리 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/ControllerAdvice.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/dto/ErrorResponse.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/AccessDeniedGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/AuthGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/InvalidGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/error/exception/NotFoundGroupException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/template/RspTemplate.java
> Feat(#1): 프로젝트 세팅

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/Member.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/Role.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/SocialType.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/repository/MemberRepository.java
>  #6
> member entity 생성
> socialType 생성
> Feat(#6): member entity 생성

- build.gradle
- src/main/resources/application.yml
- src/main/resources/logback.xml
> #1 
> 디스코드와 연동하여 로그백 적용. 
> 추후 운영서버와 개발서버 로그백 나눌예정
> Feat(#1): logback 설정

- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/QuerydslConfig.java
> #15 
>  queryDSL 의존성과 설정파일 추가
> Feat(#15): queryDSL 설정

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/JpaAuditingConfig.java
> #12 
> JpaAuditingConfig 파일 설정
> Feat(#12): JpaAuditingConfig 파일 설정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/request/BlockUpdateReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/Block.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/exception/BlockNotFoundException.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
> #11, #18
> 블록 수정기능을 구현했습니다.
> 블록 수정 테스트 코드 구현
> Feat(#11): Block 수정 기능, 수정 테스트 코드 구현

- .github/workflows/deploy.yml
> feat(#14): deploy.yml 추가

- Dockerfile
> Feat(#14): docker파일 추가

- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/AuthController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/request/RefreshTokenReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/request/TokenReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/response/AccessAndRefreshTokenResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/response/MemberLoginResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/response/UserInfo.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthMemberService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthServiceFactory.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/TokenService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/jwt/domain/Token.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/exception/OAuthException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/domain/Member.java
- src/main/resources/application.yml
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/api/AuthControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthMemberServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthServiceFactoryTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/TokenServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/jwt/TokenProviderTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/jwt/domain/TokenTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/jwt/domain/repository/TokenRepositoryTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/member/domain/repository/MemberRepositoryTest.java
>  #6 , #20 
> 로그인/회원가입 기능을 구현했습니다.
> 로그인/회원가입 테스트코드를 구현했습니다.
> 테스트코드는 추가적으로 더 작성할 예정입니다.
> Feat(#6 #20): 로그인/회원가입 기능 / 테스트코드 작성

- .github/workflows/deploy.yml
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthService.java
- src/main/resources/application.yml
> Refactor: yml 파일 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/Block.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/exception/InvalidProgressException.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
> #11, #18
> 불필요한 수정을 막기 위해 블록의 제목과 내용이 기존과 동일하다면 수정을 하지않습니다.
> 블록 상태 수정하는 기능을 구현합니다.
> Feat(#11 #18): 블록 제목과 내용이 기존과 동일하면 수정 X, 블록 상태 수정

- .github/workflows/deploy.yml
- build.gradle
- src/docs/asciidoc/block.adoc
- src/docs/asciidoc/index.adoc
- src/test/java/shop/kkeujeok/kkeujeokbackend/example/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/restdocs/RestDocsHandler.java
> ex) #33
> restdocs를 위한 build.gradle과 adoc 파일을 추가하였습니다
> Feature(#33): restdocs 적용

- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/resources/application.yml
> #18 
> 테스트용 .yml 파일을 추가합니다.
테스트 클래스에 ActiveProfiles("test") 어노테이션을 사용하여 적용해줍니다.
추후 따로 테스트 클래스를 만들어, 상속해줄 예정입니다.
> Test(#18): test yml 파일 추가, 적용

- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/api/AuthControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthMemberServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthServiceFactoryTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/auth/application/TokenServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/jwt/TokenProviderTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/jwt/domain/TokenTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthServiceTest.java
> Test(#20): yml 파일 적용 코드 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/AppConfig.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthServiceTest.java
> RestTemplate를 객체 생성이 아닌 의존성 주입으로 수정하였습니다.
> Refactor: RestTemplate 의존성 주입으로 수정

- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/reqeust/ChallengeSaveReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/converter/CycleDetailsConverter.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Cycle.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/CycleDetail.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/exception/CycleDetailsNotFoundException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/exception/InvalidCycleDetailsConversionException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/exception/InvalidCycleException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/entity/Status.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/exception/MemberNotFoundException.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/converter/CycleDetailsConverterTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/ChallengeTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/common/annotation/ControllerTest.java
> #50
> 챌린지 생성 기능 구현했습니다.
> 주기를 저장할 때, 데이터베이스에 json 배열로 저장했는데 어떤가요? 더 좋은 방법이 있을까요?
> 챌린지 생성 기능 구현

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/Block.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepositoryImpl.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/domain/BlockTest.java
> Refactor: status 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
> #11 
> RequestParam에 name 속성 추가
> Refactor(#11): RequestParam에 name 속성 추가

- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
> Test(#62): 개인 대시보드 ControllerTest 반환 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
> #11 #18 
> 블록의 타입이 추가됨으로써 반환 값이 추가되고, 반환 값이 추가되면서 테스트 코드를 수정하였습니다.
> Refactor(#11 #18): 블록 반환 값 추가, 반환 값 추가로 인한 테스트 코드 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/reqeust/ChallengeSaveReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/api/dto/response/ChallengeInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Category.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/Challenge.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/challenge/domain/repository/ChallengeCustomRepositoryImpl.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/application/ChallengeServiceTest.java
> #81 
> 챌린지 기능에 카테고리를 추가하였습니다.
> Feat(#81): 챌린지 카테고리 추가

- src/docs/asciidoc/peronsalDashboard.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardCategoriesResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardServiceTest.java
> #62 
> 사용자의 개인 대시보드 카테고리를 리스트로 반환합니다.
> Feat(#62): 사용자의 개인 대시보드 카테고리 조회 기능 구현

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/QuerydslConfig.java
> Fix(#92): Build시에 Q클래스 생성되지 않는 버그

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardListResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/response/TeamDashboardListResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/domain/repository/PersonalDashboardRepositoryTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/TeamDashboardControllerTest.java
> Revert "Refactor(#88): 개인, 팀 대시보드 전체 조회 페이지네이션 제거 (#89)"

- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
> #18 
> 테스트 코드의 파라미터에 페이지와 사이즈를 추가하였습니다.
> Refactor(#18): 테스트 코드 페이지, 사이즈 파라미터 추가

- src/docs/asciidoc/block.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepositoryImpl.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockRepositoryTest.java
> #100 
> 삭제된 블록을 불러오는 기능과 영구 삭제 기능을 구현했습니다.
휴지통에서 사용될 API입니다.
> Feat(#100): 삭제된 블록 조회, 영구 삭제 기능, 테스트 코드 구현

- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/AuthController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/api/dto/response/IdTokenResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/auth/application/AuthServiceFactory.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/GoogleAuthService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/oauth/KakaoAuthService.java
> Refactor: authServiceFactory로 id토큰 반환하는 로직 수정, JsonNode 반환 방법 DTO 사용

- src/docs/asciidoc/teamDocument.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/TeamDocumentController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/FindTeamDocumentReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/TeamDocumentReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/request/TeamDocumentUpdateReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/FindTeamDocumentResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentCategoriesResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentDetailResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/dto/response/TeamDocumentResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/application/TeamDocumentService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/TeamDocument.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/domain/repository/TeamDocumentRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/exception/TeamDocumentNotFoundException.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/teamdoc/api/TeamDocumentControllerTest.java
> #106 
> 팀 문서 새롭게 만들었습니다.
> 테코 다시 짤 예정..
> Feat(#106): 팀 문서 전체적인 작업

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
> #112
> 사용자 사진 반환 값 추가, 테스트 코드 수정
> Refactor(#112): 사용자 사진 반환 값 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/exception/UnauthorizedAccessException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardCategoriesResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardServiceTest.java
> #110 
> 대시보드 접근 권한을 수정합니다.
카테고리 중복이 안되게합니다.
> Refactor(#110): 대시보드 접근 권한 수정, 카테고리 중복 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/exception/UnauthorizedAccessException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardCategoriesResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/PersonalDashboardControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardServiceTest.java
> Fix(#110): 404에러 발생 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/api/dto/response/TeamDashboardInfoResDto.java
> #10 
> 팀 대시보드 팀원에 대시보드의 생성자를 추가합니다.
> Refactor(#10): 팀 대시보드 팀원에 대시보드 생성자 추가

- src/docs/asciidoc/member.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/api/dto/response/PersonalDashboardPageListResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/TeamDashboardsAndChallengesResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageServiceTest.java
> 마이페이지 내에서 개인 대시보드 조회 기능 추가 & 상대방 프로필은 isPublic이 true인 것만 보이도록 수정
> Refactor: 마이페이지 내에서 개인 대시보드 조회 기능 추가 & 상대방 프로필은 isPublic이 true인 것만 보이도록 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/domain/TeamDashboard.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/exception/AlreadyJoinedTeamException.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/exception/NotMemberOfTeamException.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/dashboard/team/application/TeamDashboardServiceTest.java
> #155 
> 팀 대시보드 중복 참여, 참여하지 않았지만 탈퇴하려는 사용자를 예외 처리합니다.
참가자 팀 대시보드 리스트를 수정합니다.
> Refactor(#155): 팀 대시보드 중복 참여, 참여하지 않았지만 탈퇴하려는 사용자 예외 처리, 참가자 팀 대시보드 리스트 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
> #168 
> 블록 디데이 시작날짜부터 계산, 삭제된 블록 진행도 불포함
> Refactor(#168): 블록 디데이 시작날짜부터 계산, 삭제된 블록 진행도 불포함

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
> Refactor(#168): 블록 디데이 코드 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/challenge/api/ChallengeControllerTest.java
> #168 
> 블록 디데이 코드 수정으로 인한 테스트 코드 수정
> Refactor(#168): 블록 디데이 코드 수정으로 인한 테스트 코드 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/request/BlockSequenceUpdateReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
> Refactor(#194): 블록 순번 수정

- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/request/BlockSequenceUpdateReqDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/RedisConfig.java
- src/main/resources/application.yml
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
> #194 
> redis 의존성과 config 설정 파일을 추가합니다.
> Feat(#194): redis 의존성, config 파일 추가

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
> #197 
> 내 친구 목록의 조건을 수정했습니다.
기존의 로직에서는 친구 수락을 안해도 친구 목록 리스트에 있었는데, follow의 상태가 accept. 즉, 친구가 수락된 상태에서만 내 친구 목록에 뜨게 수정했습니다.
> Refactor(#197): 내 친구 목록 조건 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/api/dto/response/FollowInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/exception/AlreadyFriendsException.java
> #197 
> 전체 사람들 조회할 때 친구 신청 보낸 사람이 isFollow true로 뜨는 오류 수정.
> 이미 친구이면 에러 처리 되도록 수정.
> Feat(#197):  isFollow true로 뜨는 오류 수정, 이미 친구이면 에러 처리 되도록 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/MyPageInfoResDto.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/member/api/MemberControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/member/mypage/application/MyPageServiceTest.java
> 마이페이지 조회할 때 memberId도 나오도록 수정
> Feat(#197): 내 정보 조회할 때 memberId도 나오도록 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
> #197 
> 추천친구 이미 친구일 때 안 나오도록 수정
> Feat(#197): 추천친구 이미 친구일 때 안 나오도록 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/domain/repository/DashboardCustomRepositoryImpl.java
> #229
> 마이페이지에서 팀 대시보드 내가 참여한 것도 보이도록 수정
> Feat(#229): 마이페이지에서 팀 대시보드 내가 참여한 것도 보이도록 수정

- src/docs/asciidoc/block.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/dto/response/BlockInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/util/BlockCleanupScheduler.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/util/DDayCalculator.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockCustomRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/dashboard/personal/application/PersonalDashboardService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/domain/repository/BlockRepositoryTest.java
> #235 
> 성능 최적화를 위해 상태별 블록 조회 로직을 수정합니다.
쿼리 로직을 수정합니다.
> Refactor(#235): 상태별 블록 조회 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/mypage/api/dto/response/MyPageInfoResDto.java
> Refactor: 내 프로필 정보 반환 값 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockService.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/api/BlockControllerTest.java
- src/test/java/shop/kkeujeok/kkeujeokbackend/block/application/BlockServiceTest.java
> Refactor: 블록 상태 변경 로직 수정

- .github/workflows/deploy.yml
- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/application/FollowService.java
> 운영 서버 배포를 위한 PR

- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/NoticeController.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/response/NoticeInfoResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/api/response/NoticeListResDto.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/application/NoticeService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/domain/Notice.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/amdin/domain/repository/NoticeRepository.java
> Feat(#255): 공지 조회 기능 구현

- src/main/java/shop/kkeujeok/kkeujeokbackend/member/follow/domain/repository/FollowCustomRepositoryImpl.java
> Refactor: 추천 친구 로직 N+1 문제 해결

- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/KafkaConfig.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/consumer/KafkaConsumer.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/EmitterRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/EmitterRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/util/SseEmitterManager.java
- src/main/resources/application.yml
> #260 
- SSE 연결 관리 Redis 사용
- 메시지 브로커 kafka 적용
> Refactor(#260): 실시간 알림 기능 수정

- .github/workflows/deploy.yml
- .github/workflows/deploy_production.yml
- build.gradle
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/config/KafkaConfig.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/application/NotificationService.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/consumer/KafkaConsumer.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/EmitterRepository.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/domain/repository/EmitterRepositoryImpl.java
- src/main/java/shop/kkeujeok/kkeujeokbackend/notification/util/SseEmitterManager.java
- src/main/resources/application.yml
> #260 
> prod deploy script를 수정합니다.
> prod-deploy 수정

- src/main/java/shop/kkeujeok/kkeujeokbackend/global/filter/LoginCheckFilter.java
화이트리스트
"/api/oauth2/callback/**",
"/api/*/token",
"/api/token/access",
로만으로 수정했습니다.
> filter의 whiteList 로그인 로직만 걸기

- .gitignore
- src/docs/asciidoc/block.adoc
- src/docs/asciidoc/challenge.adoc
- src/docs/asciidoc/follow.adoc
- src/docs/asciidoc/index.adoc
- src/docs/asciidoc/login.adoc
- src/docs/asciidoc/member.adoc
- src/docs/asciidoc/notification.adoc
- src/docs/asciidoc/personalDashboard.adoc
- src/docs/asciidoc/teamDashboard.adoc
- src/docs/asciidoc/teamDocument.adoc
- src/main/java/shop/kkeujeok/kkeujeokbackend/global/filter/LoginCheckFilter.java
> Filter 범위를 수정합니다.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Refactor: Filter 범위 수정
